name: RomainBastide
favicon: null
layout_spectrum: 0.5389280132949352
typography_spectrum: 0.6979870856739581
title: This is your new home
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5412436525803059
  lightness: 0.08872721833176911
  saturation: 0.163112715119496
  rhythmicContrast: 0.884981571463868
purpose: []
